### ISSUE TITLE
Unified baseclass for names, logging, data-lineage et al.

### ISSUE THREAD

**Issue by wilhelmagren** [wilhelmagren/synd#4]
Problem: for each specific new baseclass as of today we are implementing naming, logging etc the same way, but in multiple places.

Suggestion: implement a baseclass in `synd` which all other classes can inherit from, which implements a set of unified needs/functionalities across the entire lib.

e.g. `Base`

// Wilhelm :wave:

**Comment by Iamhero337** [comment]
Hey, Can you guide me a little What do I have to do here.

**Comment by wilhelmagren** [comment]
Sure! Mostly these issues I create are mostly so that I remember what i have to to, but I can elaborate. Nice that you want to contribute! :smiley: 

If you look under main branch, and `synd.datautil` there are two classes `Sampler` and `Transformer` which both implement base naming conventions for the classes. But doing this for all types of classes is repetitive, so we should only do this once, with a single class.

For example, with 
```python
class Base(object):
   def __init__(self, *args, **kwargs):
        cls_ = kwargs.get('cls_', self)
        name = kwargs.get('name', None)

        if name is None:
            name = cls_.__class__.__name__ + create_timestamp()

        log.debug(f'setting `{cls_.__class__.__name__}` name to: `{name}`')
        self._name = name

    def __repr__(self) -> String:
        return f'<{self.__class__.__name__} at {hex(id(self))}>'

    def __str__(self) -> String:
        return self._name
```

and then we can remove the `Transformer` and `Sampler` implementations under `synd.datautil`, and have all other classes inherit from Base :+1:

**Comment by wilhelmagren** [comment]
I have no set contribution guidelines yet, but any contributions of any form are very much welcome!

**Comment by wilhelmagren** [comment]
Of course, which kinda goes without saying, please do the implementations towards a new branch and then create a PR :+1:
